workspace = "mastadon/mastodon"

[proxy]
metadata-hints = ["project=mastodon"]

[adapters.docker]
tag = "mastodon-container-images"
cache-mode = "max"
metadata-hints = ["lane=container-images"]

[adapters.ccache]
tag = "mastodon-container-ccache"
metadata-hints = ["lane=container-images", "tool=ccache"]
