workspace = "mastadon/mastodon"

[proxy]
metadata-hints = ["project=mastodon"]

[adapters.docker]
tag = "mastodon-release-images"
cache-mode = "max"
metadata-hints = ["lane=release-images"]

[adapters.ccache]
tag = "mastodon-release-ccache"
metadata-hints = ["lane=release-images", "tool=ccache"]
